### ISSUE TITLE
Более гибкий поиск

### ISSUE THREAD

**Issue by wiyegate** [WendyH/api.lostcut.net#1]
Здравствуйте.
Было бы неплохо если бы в API для HDKinoteatr.com сделали бы более гибкий фильтр

http://api.lostcut.net/hdkinoteatr/#videos

Как я понял я могу в параметре category указать несколько категорий, например 24,7 (Аниме, боевик)
И так же со странами, а вот исключить из поиска нет, было бы отлично если можно было бы и исключающие страны и категории можно было бы указывать

**Comment by WendyH** [comment]
Оке. Как вернусь из отпуска, сделаю. Я это реализовал потом в http://api.lostcut.net/hdgo/#videos
Сделаю также.
Логика такая: если стоит знак минус первым, а потом перечисляются коды стран или категорий, то будут включены все, за исключением указанных. После 23-го августа.

**Comment by wiyegate** [comment]
В документации api увидел что появилась информация о том что через минус исключения указываются, попробовал, не работает
http://api.lostcut.net/hdkinoteatr/videos?category=7,-24&ord=-year
всё-равно аниме показывает, хотя как я понял по этой ссылке данный жанр должен был исключиться из результатов

**Comment by wiyegate** [comment]
[https://github.com/WendyH/api.lostcut.net/issues/2](url)

**Comment by WendyH** [comment]
Только сегодня реализовал это в hdkinoteatr. Проверьте.

**Comment by wiyegate** [comment]
Проверил, работает. Спасибо
