### ISSUE TITLE
Поиск выдает всё подряд

### ISSUE THREAD

**Issue by wiyegate** [WendyH/api.lostcut.net#2]
В документации api указано что через минус исключения указываются. Но не работает
http://api.lostcut.net/hdkinoteatr/videos?category=7,-24&ord=-year
всё-равно аниме показывает, хотя как я понял по этой ссылке данный жанр должен был исключаться из результатов

**Comment by WendyH** [comment]
Закрыл из-за дублирования, вопрос по сути тот же https://github.com/WendyH/api.lostcut.net/issues/1
